"""Freeze the Climate Release file inventory, expected outputs and ZIP."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

import numpy as np


def digest(path: Path) -> str:
    value = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            value.update(chunk)
    return value.hexdigest()


def describe(file: Path, root: Path, anchors: dict) -> dict:
    relative = file.relative_to(root).as_posix()
    rows = None
    columns = None
    shape = None
    dtype = None
    if file.suffix == ".npy":
        array = np.load(file, mmap_mode="r", allow_pickle=False)
        shape = list(array.shape)
        rows = shape[0] if shape else 1
        dtype = str(array.dtype)
    elif file.suffix == ".csv":
        with file.open(newline="", encoding="utf-8-sig") as handle:
            reader = csv.reader(handle)
            columns = next(reader, [])
            rows = sum(1 for _ in reader)
    elif file.suffix == ".jsonl":
        with file.open(encoding="utf-8") as handle:
            first = handle.readline()
            columns = list(json.loads(first)) if first else []
            rows = int(bool(first)) + sum(1 for _ in handle)
    elif file.suffix == ".json":
        payload = json.loads(file.read_text(encoding="utf-8"))
        columns = list(payload) if isinstance(payload, dict) else None
        rows = len(payload) if isinstance(payload, list) else 1
    if relative.startswith("source_safe/"):
        source = "byte-identical Climate feature from frozen Bundle: " + relative.removeprefix("source_safe/")
    elif relative.startswith(("selection_fit/", "test_features/")):
        source = "code/prepare_climate.py: frozen Bundle row slice; mapping.csv supplies row identity"
    elif relative == "weekly_axis.csv":
        source = "date/index fields only from frozen Climate clean numeric snapshot"
    elif relative == "source_lineage_slim.csv":
        source = "Climate metadata subset of seventh-round frozen text_lineage.csv"
    elif relative.startswith("text_trace/"):
        source = "byte-identical Climate text_trace from frozen Bundle"
    elif relative == "EXPECTED_OUTPUTS.json":
        source = "SHA256 of reference replay outputs, generated by code/verify_climate.py"
    else:
        source = "eighth-round frozen build/verification code or derived metadata"
    return {"relative_path": relative, "bytes": file.stat().st_size, "rows": rows,
            "columns": columns, "shape": shape, "dtype": dtype, "sha256": digest(file),
            "source": source, "bundle_signature": anchors["bundle_signature"]}


def build(root: Path) -> dict:
    anchors = json.loads((root / "source_anchors.json").read_text(encoding="utf-8"))
    files = sorted((file for file in root.rglob("*") if file.is_file()
                    and file.name != "MANIFEST.json" and "__pycache__" not in file.parts
                    and file.suffix != ".pyc"), key=lambda file: file.relative_to(root).as_posix())
    manifest = {"schema_version": 1, "bundle_signature": anchors["bundle_signature"],
                "split_spec_sha256": anchors["split_spec_sha256"],
                "self_exclusion": "MANIFEST.json has no self-hash to avoid a circular commitment.",
                "files": [describe(file, root, anchors) for file in files]}
    (root / "MANIFEST.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    return manifest


def package(root: Path, output: Path, manifest: dict) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with ZipFile(output, "w", compression=ZIP_DEFLATED, compresslevel=9) as archive:
        for relative in sorted([entry["relative_path"] for entry in manifest["files"]] + ["MANIFEST.json"]):
            archive.write(root / relative, relative)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("release_root", type=Path)
    parser.add_argument("--reference-output", type=Path)
    parser.add_argument("--zip", type=Path)
    args = parser.parse_args()
    root = args.release_root.resolve(strict=True)
    if args.reference_output:
        reference = args.reference_output.resolve(strict=True)
        report = json.loads((reference / "replay_report.json").read_text(encoding="utf-8"))
        expected = {"files": {name: digest(reference / name) for name in report["output_sha256"]}}
        (root / "EXPECTED_OUTPUTS.json").write_text(json.dumps(expected, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    manifest = build(root)
    if args.zip:
        package(root, args.zip.resolve(), manifest)
    print(json.dumps({"manifest_files": len(manifest["files"]), "manifest_sha256": digest(root / "MANIFEST.json")}, ensure_ascii=False))
